### ISSUE TITLE
State of module

### ISSUE THREAD

**Issue by nicholas12345** [omega8cc/hosting_advanced_cron#1]
Hi,
I see you started porting this very useful contributed module that is missing for Aegir 3.
I gave a try to this version and I see it is still work in progress, as there are debug statements, errors and notices. And functionality doesn't work either. 
So here is a quick list of stuff I captured during test:
During installation:
`DatabaseSchemaObjectExistsException: Table hosting_advanced_cron already exists. in DatabaseSchema->createTable() (line 660 of /path/to/hostmaster-7.x-3.2/includes/database/schema.inc).`

When viewing / editing site:
`Notice: Undefined property: stdClass::$cron_interval in hosting_advanced_cron_node_view() (line 156 of /path/to/hostmaster-7.x-3.2/sites/all/modules/hosting_advanced_cron/hosting_advanced_cron.module).`

What's the plan for this module? Do you plan to work on it further?

**Comment by omega8cc** [comment]
Hi,

There were too many issues due to the way function overrides work in D7, so we finally abandoned the attempts within separate module and instead merged it into Aegir core directly -- and it works!

Of course for non-BOA Aegir installs it could be useful to complete the D7 port as a separate module, but this code was already so heavy BOA-specific and rewritten, that it would have to have some BOA-only stuff abstracted or replaced (like the way the cron is called locally with fake headers etc).

You can see the working module in this repo: https://github.com/omega8cc/hosting/tree/feature/3.0.x-hosting/cron

**Comment by nicholas12345** [comment]
Thanks! I do not use BOA (though I have on TODO to try it out), so I replaced current Aegir's hosting cron with yours from the repo you provided. 
Procedure was:
- uninstall Aegir's cron
- replace Aegir's cron module with yours
- install module, configure global and per site settings

And the result is that it doesn't trigger cron after set period of time. It also throws after installation and on each site tab view:

> Notice: Undefined property: stdClass::$cron_interval in hosting_cron_node_load() (line 137 of /path/to/aegir/hostmaster-7.x-3.2/sites/all/modules/cron/hosting_cron.module).

Which probably means it is either too specific implementation for BOA or I did something wrong.

**Comment by omega8cc** [comment]
The module has been rewritten for BOA a long time ago, and currently the version we have merged in our hosting fork will not work on a non-BOA installs. It comes with upgrade path, but again, it works only for BOA instances. It is not a drop-in replacement.

**Comment by nicholas12345** [comment]
Ok thanks. Closing
